[package]
name = "fuzzsuite"
version = "0.1.0"
authors = ["Bruno Zimmermann <brunoczim@gmail.com>"]
publish = false

[dependencies]
lazy_static = "1"
lockfree = { path = "../../" }
owned-alloc = "0.2"
